server:

  port: 8080

spring:

  application:
    name: smartcampus-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://SmartCampus:HUhsUVKQeWQW2cr8@cluster0.ne2wk3x.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
