server:

  port: 8080

spring:

  application:
    name: smartcampus-backend
  data:
    mongodb:
      uri: "${MONGODB_URI:mongodb://SmartCampus:HUhsUVKQeWQW2cr8@ac-8y9loh2-shard-00-00.ne2wk3x.mongodb.net:27017,ac-8y9loh2-shard-00-01.ne2wk3x.mongodb.net:27017,ac-8y9loh2-shard-00-02.ne2wk3x.mongodb.net:27017/smartcampus?ssl=true&replicaSet=atlas-rbg5gv-shard-0&authSource=admin&retryWrites=true&w=majority}"
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
