server:

  port: 8080

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  mail:
    from: ${APP_MAIL_FROM:no-reply@smartcampus.local}

spring:

  application:
    name: smartcampus-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://SmartCampus:HUhsUVKQeWQW2cr8@cluster0.ne2wk3x.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:1088875106108-g39vcf5i5nvrveojnuh7mukdhsaq2iuo.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            issuer-uri: https://accounts.google.com
            user-name-attribute: sub

management:
  endpoints:
    web:
      exposure:
        include: health,info
